---
title: "Course Project 1"
output: html_document
---

## Plot 4


```{r }
setwd("C:/Users/Anhuynh/Desktop/Data Science_Cousera/Exploratory Data Analysis/Assignment")

data <- read.csv("household_power_consumption.txt", header = TRUE, sep = ";", quote = "\"", na.strings = "?", nrows = 2075259, check.names = TRUE)
data_extract <- subset(data, Date %in% c("1/2/2007", "2/2/2007"))
data_extract$Date <- strptime(data_extract$Date, format = "%d/%m/%Y")

datetime <- paste(as.Date(data_extract$Date), data_extract$Time)
data_extract$DateTime <- as.POSIXct(datetime)

par(mfrow = c(2, 2), mar = c(4, 4, 2, 1), oma = c(0, 0, 2, 0))

with(data_extract, plot(Global_active_power~DateTime, type="l", xlab = "", ylab = "Global Active Power (kilowatts)" ))

with(data_extract, plot(Voltage~DateTime, type="l", xlab = "datetime", ylab = "Voltage" ))

with(data_extract, plot(Sub_metering_1~DateTime, type="l", xlab = "", ylab = "Energy sub metering", col="black"))
with(data_extract, points(Sub_metering_2~DateTime, type="l", col="red"))
with(data_extract, points(Sub_metering_3~DateTime,type="l", col="blue"))
legend("topright", col=c("black","red","blue"), lty=1, lwd=2, legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))

with(data_extract, plot(Global_reactive_power~DateTime, type="l", xlab = "datetime", ylab = "Global_reactive_power" ))



```

## Add the PNG file


```{r }
png(file="plot4.png", width=480, height=480)

dev.off()
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
